#!/bin/bash

#
# Command runner
#

set -e 

SCRIPT_PATH=`readlink --canonicalize $0`
SCRIPT_DIR=`readlink --canonicalize $(dirname $0)`
CRORSE_LIB_DIR="$SCRIPT_DIR/crorse-lib"

## Start a Python shell with the crorse package and other useful modules loaded
function crorse_shell() {
    source "$CRORSE_LIB_DIR/.venv/bin/activate"
    cd $CRORSE_LIB_DIR && PYTHONSTARTUP=$CRORSE_LIB_DIR/pythonrc.py python 
} 

## Run the scraper
function scrape() {
    source "$CRORSE_LIB_DIR/.venv/bin/activate"
    set -x
    cd "$CRORSE_LIB_DIR" && python -m crorse.extra.scrape
}

## Show commands with help text
function help() {
    echo "Usage: run COMMAND"
    PYSCRIPT=$(cat << HEREDOC_END
import sys, re;
txt = sys.stdin.read();
matches = re.findall(r"^## (.*)$\n^function (.*)\(\)", txt, flags=re.MULTILINE);
print("Commands:\n" + "\n".join(f"\033[1;36m  {name}\033[0;0m\n    {desc}"
      for desc, name in sorted(matches, reverse=True)))
HEREDOC_END
)

cat "$SCRIPT_PATH" | python -c "$PYSCRIPT"
}

if [ -z "$1" ]; then
    help
    exit 1
fi

FUNCTIONS=`declare -F | sed 's/declare -f //'`
if `echo "$FUNCTIONS" | grep --word-regexp --quiet "$1"`; then
    "$1" "${@:2}"  # Slice at 2 so that arguments in functions start at $1
else
    echo "Invalid command: $1"
    help
    exit 1
fi
